// insuranceData.js
export const insurancePlans = [
  {
    id: 1,
    provider: "Bao Viet Insurance",
    planName: "HealthCare Plus",
    coverage: 1000000000, // Số tiền bảo hiểm tối đa
    monthlyPremium: 800000, // Phí bảo hiểm hàng tháng
    minAge: 18, // Tuổi tham gia tối thiểu
    maxAge: 60, // Tuổi tham gia tối đa
    minSalary: 10000000, // Thu nhập tối thiểu
    benefits: ["Hospitalization", "Surgery", "Outpatient", "Dental"],
    conditions: ["No pre-existing conditions", "Non-smoker preferred"],
    riskFactors: ["age", "health_history", "occupation"],
    lifestylePreferences: ["active", "moderate"],
  },
  {
    id: 2,
    provider: "Prudential Vietnam",
    planName: "Family Care",
    coverage: 800000000,
    monthlyPremium: 650000,
    minAge: 18,
    maxAge: 65,
    minSalary: 8000000,
    benefits: ["Hospitalization", "Critical Illness", "Accident"],
    conditions: ["Family coverage available"],
    riskFactors: ["family_history", "lifestyle"],
    lifestylePreferences: ["sedentary", "moderate"],
  },
  {
    id: 3,
    provider: "Bảo Việt Nhân Thọ",
    planName: "An Phát Trọn Đời",
    coverage: 2000000000,
    monthlyPremium: 1000000,
    minAge: 0,
    maxAge: 65,
    minSalary: 5000000,
    benefits: [
      "Bảo vệ trọn đời",
      "Hỗ trợ tài chính khi mắc bệnh hiểm nghèo",
      "Quyền lợi đáo hạn hấp dẫn",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 4,
    provider: "Manulife Việt Nam",
    planName: "Manulife - Cuộc Sống Tươi Đẹp",
    coverage: 1500000000,
    monthlyPremium: 900000,
    minAge: 18,
    maxAge: 60,
    minSalary: 7000000,
    benefits: [
      "Bảo vệ trước 134 bệnh lý nghiêm trọng",
      "Hỗ trợ chi phí y tế",
      "Quyền lợi tử vong",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 5,
    provider: "AIA Việt Nam",
    planName: "AIA - Sống Khỏe",
    coverage: 1200000000,
    monthlyPremium: 750000,
    minAge: 18,
    maxAge: 65,
    minSalary: 6000000,
    benefits: [
      "Bảo vệ trước bệnh ung thư",
      "Hỗ trợ chi phí điều trị",
      "Quyền lợi tử vong do tai nạn",
    ],
    conditions: ["Không áp dụng cho người có bệnh ung thư trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 6,
    provider: "Generali Việt Nam",
    planName: "VITA - Sống Tự Tin",
    coverage: 1800000000,
    monthlyPremium: 850000,
    minAge: 0,
    maxAge: 70,
    minSalary: 8000000,
    benefits: [
      "Bảo vệ trước 111 bệnh hiểm nghèo",
      "Quyền lợi tử vong và thương tật toàn bộ vĩnh viễn",
      "Hỗ trợ chi phí y tế",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 7,
    provider: "Prudential Việt Nam",
    planName: "PRU - Cuộc Sống Bình An",
    coverage: 1000000000,
    monthlyPremium: 700000,
    minAge: 18,
    maxAge: 65,
    minSalary: 6000000,
    benefits: [
      "Bảo vệ trước bệnh hiểm nghèo",
      "Hỗ trợ chi phí y tế",
      "Quyền lợi tử vong",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 8,
    provider: "FWD Việt Nam",
    planName: "FWD - Bảo Hiểm Căn Bệnh Hiểm Nghèo",
    coverage: 1200000000,
    monthlyPremium: 820000,
    minAge: 18,
    maxAge: 65,
    minSalary: 7000000,
    benefits: [
      "Hỗ trợ tài chính ngay khi phát hiện bệnh hiểm nghèo",
      "Quyền lợi tử vong",
      "Hỗ trợ chi phí điều trị",
    ],
    conditions: ["Không áp dụng cho bệnh hiểm nghèo hiện tại"],
    riskFactors: ["sức khỏe", "gia đình", "tuổi tác"],
    lifestylePreferences: ["chăm sóc sức khỏe tốt", "không hút thuốc"],
  },
  {
    id: 9,
    provider: "Chubb Việt Nam",
    planName: "Chubb - Bảo Hiểm Du Lịch",
    coverage: 200000000,
    monthlyPremium: 500000,
    minAge: 0,
    maxAge: 80,
    minSalary: 0,
    benefits: [
      "Bảo vệ khi đi du lịch quốc tế",
      "Hỗ trợ chi phí y tế khẩn cấp",
      "Quyền lợi hủy chuyến đi",
    ],
    conditions: ["Không bảo vệ trong trường hợp tự ý bỏ hành trình"],
    riskFactors: ["phạm vi quốc gia", "mục đích du lịch"],
    lifestylePreferences: ["thích du lịch", "chủ động"],
  },
  {
    id: 10,
    provider: "Hanwha Life",
    planName: "Hanwha - An Khang",
    coverage: 1000000000,
    monthlyPremium: 750000,
    minAge: 18,
    maxAge: 60,
    minSalary: 6000000,
    benefits: [
      "Quyền lợi bảo hiểm sức khỏe",
      "Hỗ trợ khi mắc bệnh hiểm nghèo",
      "Hỗ trợ chi phí khám chữa bệnh",
    ],
    conditions: ["Không hút thuốc trong 3 năm gần đây"],
    riskFactors: ["sức khỏe", "lịch sử bệnh tật"],
    lifestylePreferences: ["thích thể thao", "không hút thuốc"],
  },
  {
    id: 11,
    provider: "Liberty Insurance",
    planName: "Liberty - Xe Cộ Toàn Diện",
    coverage: 150000000,
    monthlyPremium: 1200000,
    minAge: 18,
    maxAge: 60,
    minSalary: 0,
    benefits: [
      "Bảo vệ xe cộ",
      "Bồi thường tai nạn giao thông",
      "Hỗ trợ pháp lý sau tai nạn",
    ],
    conditions: ["Không áp dụng cho xe cũ quá 10 năm"],
    riskFactors: ["loại xe", "tần suất lái xe"],
    lifestylePreferences: ["sở hữu xe", "cẩn thận"],
  },
  {
    id: 12,
    provider: "Bảo Minh",
    planName: "Bảo Minh - Tai Nạn Cá Nhân",
    coverage: 500000000,
    monthlyPremium: 300000,
    minAge: 5,
    maxAge: 70,
    minSalary: 0,
    benefits: [
      "Bồi thường tai nạn",
      "Hỗ trợ viện phí",
      "Quyền lợi tử vong và thương tật",
    ],
    conditions: ["Không áp dụng cho người có nghề nguy hiểm cao"],
    riskFactors: ["nghề nghiệp", "tuổi"],
    lifestylePreferences: ["người lao động", "tích cực"],
  },
  {
    id: 13,
    provider: "Bảo Việt",
    planName: "Bảo Việt An Gia",
    coverage: 454000000, // Số tiền bảo hiểm tối đa
    monthlyPremium: 500000, // Phí bảo hiểm hàng tháng
    minAge: 0, // Tuổi tham gia tối thiểu
    maxAge: 65, // Tuổi tham gia tối đa
    minSalary: 0, // Thu nhập tối thiểu
    benefits: [
      "Bảo vệ toàn diện với 5 chương trình tùy chọn: Đồng, Bạc, Vàng, Bạch Kim, Kim Cương",
      "Chi trả quyền lợi lên đến 454 triệu đồng/người/năm",
      "Hỗ trợ chi phí nằm viện, phẫu thuật, và các dịch vụ y tế khác",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 14,
    provider: "Manulife Việt Nam",
    planName: "An Tâm Vui Sống 2.0",
    coverage: 2000000000,
    monthlyPremium: 850000,
    minAge: 18,
    maxAge: 60,
    minSalary: 7000000,
    benefits: [
      "Bảo vệ cả gia đình với quyền lợi hoàn phí lên đến 110%",
      "Lựa chọn đóng phí ngắn hạn cho bảo vệ dài hạn",
      "Gia tăng bảo vệ với các sản phẩm bổ trợ chăm sóc sức khỏe",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
  {
    id: 15,
    provider: "Manulife Việt Nam",
    planName: "Hành Trình Hạnh Phúc",
    coverage: 3000000000,
    monthlyPremium: 950000,
    minAge: 18,
    maxAge: 65,
    minSalary: 8000000,
    benefits: [
      "Bảo vệ lên đến 400% số tiền bảo hiểm trước rủi ro tử vong do tai nạn",
      "Linh hoạt lựa chọn gói bảo hiểm và thời hạn đóng phí",
      "Các khoản thưởng đều đặn và hấp dẫn",
    ],
    conditions: ["Không áp dụng cho người có bệnh lý nghiêm trọng trước đó"],
    riskFactors: ["tuổi", "tiền sử bệnh tật", "nghề nghiệp"],
    lifestylePreferences: ["không hút thuốc", "lối sống lành mạnh"],
  },
];
